name: AniList Sync

on:
  schedule:
    - cron: "0 3 * * *"
  workflow_dispatch:
    inputs:
      mode:
        description: "Mode de synchro"
        required: true
        default: "update"
        type: choice
        options:
          - update
          - backfill
      backfill_limit:
        description: "Nombre d'animes à récupérer en backfill"
        required: false
        default: "500"

jobs:
  sync:
    runs-on: ubuntu-latest
    env:
      FIREBASE_SERVICE_ACCOUNT_JSON: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_JSON }}
      UPDATE_LIMIT: "200"
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install dependencies
        run: npm install

      - name: Run AniList sync
        run: |
          if [ "${{ github.event_name }}" = "workflow_dispatch" ] && [ "${{ inputs.mode }}" = "backfill" ]; then
            BACKFILL_LIMIT="${{ inputs.backfill_limit }}" node scripts/anilist-sync.js backfill
          else
            node scripts/anilist-sync.js update
          fi